### ISSUE TITLE
C++ style comment in platform-top.h breaks build

### ISSUE THREAD

**Issue by stevenbell** [Avnet/petalinux#1]
On my system, the C++ style comment at the end of platform-top.h for the IOCC (here: https://github.com/Avnet/petalinux/blob/master/configs/u-boot/platform-top.h.uz3eg_iocc_dp#L55) causes the build to fail with an error about the `//` comment:

```
In file included from include/config.h:5:0,
                 from /nobackup/sebell/work/ultrazed/petalinux/projects/uz3eg_iocc_dp_2017_2//Cbuild/tmp/work/plnx_aarch64-xilinx-linux/u-boot-xlnx/v2017.01-xilinx-v2017.2+gitAUTOINC+5290eb544b-r0/git/arch/arm/cpu/armv8/u-boot.lds:11:
/nobackup/sebell/work/ultrazed/petalinux/projects/uz3eg_iocc_dp_2017_2/build/tmp/work/plnx_aarch64-xilinx-linux/u-boot-xlnx/v2017.01-xilinx-v2017.2+gitAUTOINC+5290eb544b-r0/git/include/configs/platform-top.h:55:1: error: C++ style comments are not allowed in ISO C90
 //#undef CONFIG_SYS_BOOTMAPSZ
 ^
```

Is there something about my setup (e.g., compiler or C version flag) that's wrong?

**Comment by AlbertaBeef** [comment]
You are correct, that format of comment is invalid.

Please delete the lines or change to /* … */ style comment.

I will have this fixed in next version that is checked-in …

Regards,

Mario Bergeron

**Comment by sharvin-vittappan** [comment]
Hi,
I also face the same issue.
I am running petalinux and Vivado of version 2017.2 in Ubuntu of version 	"Ubuntu 16.04.5 LTS".
@AlbertaBeef How can I use the version with this fix since u mentioned that " will have this fixed in next version that is checked-in …"

Thanks
