### ISSUE TITLE
Minized 2019.1 build error

### ISSUE THREAD

**Issue by bartokon** [Avnet/petalinux#12]
Minized EMMC enhanced bsp is unbuildable.

![erro1](https://user-images.githubusercontent.com/47795888/89267045-0134bc00-d637-11ea-8c8c-7408ff171131.PNG)
![erroe2](https://user-images.githubusercontent.com/47795888/89267050-0265e900-d637-11ea-84d7-fa308eee8ffd.PNG)

Steps to reproduce:
git clone https://github.com/Avnet/bdf.git --branch master;
git clone https://github.com/Avnet/hdl.git --branch 2019.1;
git clone https://github.com/Avnet/petalinux.git --branch 2019.1;
cd  petalinux/scripts
./make_minized_emmc_enhanced_bsp.sh

Same goes to minized_ttc

**Comment by narrucmot** [comment]
Thanks for bringing this to our attention.  These scripts are now fixed on the 2019.1 branch.

--Tom
