### ISSUE TITLE
common.sh script can't find right tag for hdl or petalinux repository.

### ISSUE THREAD

**Issue by wknitter** [Avnet/petalinux#20]
Line 133 in common.sh returns a null value for the repo tag when trying to run any of the BSP scripts.
![Screenshot from 2020-11-04 14-37-38](https://user-images.githubusercontent.com/4765918/98159914-5fc63c00-1eab-11eb-97e8-32aad32bdd7d.png)

**Comment by zedman2000** [comment]
Hi there, we are just now validating things and you need to checkout again.  I just switched up the tags this morning and that was one of the things that we corrected.

**Comment by wknitter** [comment]
Hi Daniel,

I just rechecked out the 2020.1 branch and I am getting the same issue. Were the updates you made this morning in the master branch?

Whitney Knitter
Email: whitney@knitronics.com<mailto:whitney@knitronics.com>
Phone: 816-308-6964

[cid:6C50C4A4-22C1-45FF-8157-96D1EDE58C65@fios-router.home]

On Nov 4, 2020, at 3:29 PM, Daniel Rozwood <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi there, we are just now validating things and you need to checkout again. I just switched up the tags this morning and that was one of the things that we corrected.

**Comment by wknitter** [comment]
Hi Daniel,

I just rechecked out the 2020.1 branch and I am getting the same issue. Were the updates you made this morning in the master branch?

Whitney

**Comment by narrucmot** [comment]
Hi Whitney,  you caught us in the process of tagging our BSPs for online release.  For your use right now you can edit the common.sh file and change the BUILD_FROM_TAG shell variable to "false".

**Comment by narrucmot** [comment]
Dan and I are working on the 2020.1 branch.

**Comment by zedman2000** [comment]
Hi Whitney, 

You can also use the tag:
2020p1_ultra96v2_oob_ULTRA96V2_20201104_065342
I am building this now.  This tag will be the official stuff going forward, unless I see a problem - which I am still building right now.

--Dan

**Comment by wknitter** [comment]
I tried the new tag, and the Vivado project builds find for the BSP, but the PetaLinux project fails with this:
![Screenshot from 2020-11-04 16-25-35](https://user-images.githubusercontent.com/4765918/98169568-80e25900-1eba-11eb-9f9b-41dd1f2361d6.png)

**Comment by zedman2000** [comment]
Strange, I am not seeing that at all.  I am nearly done with the build at this point.  Do you have all of your environmental variables setup?  Are you using the precompiled things from Xilinx (downloads.tar.gz, aarch...tar.gz, etc.)?
Did you setup your build environment based on our recommended install environment?

**Comment by wknitter** [comment]
I cloned the bdf, hdl, and petalinux repos to a local drive, then checked out the master branch of the bdf repo and the 2020.1 branch of the hdl and petalinux repos. I used your recommended install environment. I'm trying to run the make_ultra96v2.sh script, I sourced the Vivado 2020.1 settings script and the PetaLinux 2020.1 settings script. These are all the same steps I followed to successfully build the 2019.2 BSP from the 2019.2 branch.

**Comment by wknitter** [comment]
I got the above error after I followed narrucmot's advice to edit the common.sh file and change the BUILD_FROM_TAG shell variable to "false".

**Comment by zedman2000** [comment]
Hi Whitney,

I would use the tag I sent to you above and I would not change that variable.  That is what I am building and not having any issues.  If this builds and tests cleanly for me, that tag is what is going to be officially marked as the file for people to use for Ultra96V2 projects. 

--Dan

**Comment by zedman2000** [comment]
Also, thanks for the feedback.  Keep in mind, these are new pieces that we added into this version of the code, since we are now planning to support more features, we added some things around the rootfs...so knowing your feedback was valuable to us.

Thanks!

**Comment by wknitter** [comment]
Dan, 

Where do I use that tag specifically? Because when I run common.sh with BUILD_FROM_TAG set to true, it returns the tag variable it finds as null, like the tag isn't set somewhere it needs to be. I even tried running "git status head | head -n1 | cut -d ' ' -f4" from the command line directly to confirm it returns null. And "git status head | head -n1" just returns the tag of "2020.1".

**Comment by narrucmot** [comment]
For the hdl and petalinux repos you would need to checkout the tag Dan provided:
$ cd </path/to/cloned/repos>
$ cd hdl
$ git checkout 2020p1_ultra96v2_oob_ULTRA96V2_20201104_065342
$ cd ../petalinux
$ git checkout 2020p1_ultra96v2_oob_ULTRA96V2_20201104_065342
To use the tag set BUILD_FROM_TAG to "true" in petalinux/scripts/common.sh.
Verify the repo is on the tag:
$ git status head
![image](https://user-images.githubusercontent.com/12900664/98176261-2fd86200-1ec6-11eb-88c5-106f7b19ceb1.png)

If you don't see the tag named then you may need to re-clone the hdl and petalinux repositories and start over.  If you do see that the repo is on the tag then run the build script:
$ cd scripts
$ make_ultra96v2.sh

**Comment by zedman2000** [comment]
> Dan,
> 
> Where do I use that tag specifically? Because when I run common.sh with BUILD_FROM_TAG set to true, it returns the tag variable it finds as null, like the tag isn't set somewhere it needs to be. I even tried running "git status head | head -n1 | cut -d ' ' -f4" from the command line directly to confirm it returns null. And "git status head | head -n1" just returns the tag of "2020.1".

Whitney,

I think Tom has you set.  You might have some mixed files / or other goofy things as you had tip, then branch, then possible tags.
Let's get you straight to the right place to start with!

Also, Tom and I have seen where you go git checkout -b <tag> end up goofy...so please follow exactly what Tom posted.  That is how I do it and have done it and again, I have not seen the strange things you have.
![image](https://user-images.githubusercontent.com/9578884/98176804-5f26a900-1e9d-11eb-95a0-24458f0703f7.png)

I am up to clang in my build.

--Dan
