### ISSUE TITLE
Ultra96v2 2020.1 width mismatch

### ISSUE THREAD

**Issue by gjkunde** [Avnet/petalinux#22]
Hello,

I am looking for the bsp for the Ultra96v2 for Vitis 2020.1 Petalinux 2020.1,
it appears there is a script here - how would I use it ?

Respectfully gjk

**Comment by gjkunde** [comment]
My apologies

**Comment by narrucmot** [comment]
The 2020.1 PetaLinux BSP and Vitis platforms for the Ultra96-V2 have been sent to our web team to get posted online to this link:
https://www.element14.com/community/docs/DOC-95649 -> Reference Designs
