### ISSUE TITLE
Hang on Checking sstate mirror object availability

### ISSUE THREAD

**Issue by smsajjadi** [Avnet/petalinux#29]
I am trying to build the bsp for uz7ev for vivado/petalinux 2020.2

When running ./make_uz7ev_evcc_base.sh in the building of petalinux project, the process hangs on:
`Initialising tasks: 100% |#######################################| Time: 0:00:16
Checking sstate mirror object availability: 100% |###############| ETA:  0:00:00`

I have tried to wait here for long, but it seems like that no specific process is active.

**Comment by zedman2000** [comment]
Hi there,
Please use our forums on E14 for future support.
https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums
At this time, 2020.2 is not released and we are working on the various aspects of it.  Personally, I have not seen that issue, so it is probable something is not setup properly for you at this time.  However, as stated, 2020.2 is not stable at this time and I would suggest not using it at this time.

I suggest you go back to a tag or a 2020.1 tip.
http://avnet.me/DBA_BSPS_PLATFORMS_2020p1

Thanks!

--Dan
