### ISSUE TITLE
make_uz3eg_iocc.sh file does not generate bitstream 

### ISSUE THREAD

**Issue by BirsenGuler** [Avnet/petalinux#31]
Hi,

I work with avnet ultrazed 3EG IOCC board. I tried to create BSP file by using make_uz3eg_iocc.sh. But there is a error when generating bitstream.

I work with Vivado 2020.1 and petalinux 2020.1, also ubuntu 18.4.

My work flow is:

cd ~

mkdir -p git/avnet

cd git/avnet

git clone git://github.com/avnet/bdf.git -b master

git clone git://github.com/avnet/hdl.git -b 2020.1

git clone git://github.com/avnet/petalinux.git -b 2020.1

cd /home/peta-dev/git/avnet/petalinux/scripts

source /home/peta-dev/Xilinx/Vivado/2020.1/settings64.sh

source ~/petalinux/settings.sh

./make_uz3eg_iocc.sh

I encountered this error:

***** Wait for bitstream to be writen...
[Mon Mar 29 13:20:16 2021] Waiting for impl_1 to finish...
/home/peta-dev/Xilinx/Vivado/2020.1/bin/loader: line 286: 6390 killed         "$RDI_PROG" "$@"

**Comment by BirsenGuler** [comment]
[make_uz3eg_iocc_sh_problem.txt](https://github.com/Avnet/petalinux/files/6221488/make_uz3eg_iocc_sh_problem.txt)
My ubuntu screen was att

**Comment by BirsenGuler** [comment]
My ubuntu screen was attached

**Comment by narrucmot** [comment]
Hi Birsen,

How much RAM do you have installed in your Ubuntu PC?  This error message indicates you may not have enough RAM.  See this Xilinx forum post:
https://forums.xilinx.com/t5/Implementation/Implementation-error-Vivado-2020-1-bin-loader-line-286-67955/td-p/1132882

Xilinx recommends at least 6GB of RAM (more is always better!) for Vivado to build a design for the UZ3EG device:
https://www.xilinx.com/products/design-tools/vivado/memory.html

--Tom

**Comment by BirsenGuler** [comment]
Hi Tom,

I control RAM.

Thanks for realy valuable answer and suggestions.

**Comment by BirsenGuler** [comment]
Hi,
I check RAM in my Ubuntu PC :
peta-dev@petadev-Lenovo-Y520-15IKBN:~$ free -h
                     total        used        free      shared  buff/cache   available
Mem:            15G        2.0G         11G        645M        1.9G         12G
Swap:          2.0G          0B        2.0G

When vivado synthesise:

***** Wait for bitstream to be writen...
[Mon Mar 29 13:20:16 2021] Waiting for impl_1 to finish...
/home/peta-dev/Xilinx/Vivado/2020.1/bin/loader: line 286: 6390 killed "$RDI_PROG" "$@"

Again I check RAM in my Ubuntu PC :
                     total        used        free         shared  buff/cache   available
Mem:            15G        14G         143M        301M        420M         34M
Swap:          2.0G        1.5G        537M

**Comment by BirsenGuler** [comment]
![Screenshot from 2021-03-29 17-23-25](https://user-images.githubusercontent.com/81416239/112937709-cf75e580-9130-11eb-9069-794512179642.png)

**Comment by BirsenGuler** [comment]
![Uploading Screenshot from 2021-03-29 17-24-13.png…]()

**Comment by BirsenGuler** [comment]
![Screenshot from 2021-03-29 17-24-13](https://user-images.githubusercontent.com/81416239/112937756-e9172d00-9130-11eb-8acf-f2acd3782b93.png)

**Comment by zedman2000** [comment]
Hi BirsenGule,

Can you please move this over to the Element14 forums?  We provide all of our support for our repositories there.
Here is a direct link to the UltraZed forums, where you can feel free to post and link back to this to save you from recapping everything.
https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums/ultrazed-hardware-design-forum/content?filterID=contentstatus[published]~objecttype~objecttype[thread]&filterID=contentstatus[published]%7Elanguage%7Elanguage%5Bcpl%5D

Please also post if you are using an Ubuntu Virtual Machine, what version of Ubuntu, and what code you are trying to build (
You can check using something like this: git describe --tags

Thank you!
