### ISSUE TITLE
Error Generating make_uz7ev_evcc_hdmi_v.sh 

### ISSUE THREAD

**Issue by FrancoCapraro** [Avnet/petalinux#35]
Hello. Im using the 2020.2 version of petalinux , hdl and bdf:

git clone https://github.com/avnet/bdf.git -b master

git clone https://github.com/avnet/hdl.git -b 2020.2

git clone https://github.com/avnet/petalinux.git -b 2020.2

But i see that the 2020.2 branch of hdl doesnt have a "projects" folder that is called in the petalinux/scripts/common.sh :

"HDL_PROJECTS_FOLDER=${HDL_FOLDER}/projects" [LINE 51]

What im doing wrong ?

Some info about my  "setup":

source PETALINUX2020_2/settings.sh  ( WORKING )
source /tools/Xilinx/Vivado/2020.2/settings64.sh (WORKING)
cd $FOLDER_IN_MY_PC/avnet 
ls
bdf  hdl  petalinux

**Comment by narrucmot** [comment]
Starting with the 2020.2 branch the "projects" folder is only used for output files and thus is not source controlled via git.  The folder will be created by the Vivado build script when that script is run.

If you are using these gits repositories to build a Vivado project or PetaLinux BSP you may mind these recent blog posts useful:
[https://www.element14.com/community/groups/fpga-group/blog/2021/04/29/avnet-hdl-git-howto-vivado-20201-and-later](url)
[https://www.element14.com/community/groups/fpga-group/blog/2021/04/29/using-avnet-build-scripts-to-build-a-petalinux-bsp-20201-and-later](url)

In the future, we ask that users of our git repositories ask their questions on the user forums at Element14.com: [https://www.element14.com/community/community/designcenter/zedboardcommunity/zedboard-forums/places?filterID=all](url)

--Tom
